version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    open-pull-requests-limit: 25
    schedule:
      interval: "daily"
      time: "13:00"

  - package-ecosystem: 'github-actions'
    directory: '/'
    open-pull-requests-limit: 25
    schedule:
      interval: 'daily'
