spring:
  jpa:
    hibernate:
      ddl-auto: validate

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://0.0.0.0:5432/postgres
    username: postgres
    password: postgres