on:
  push:
    branches:
      - main

name: Deploy to Fly.io

jobs:
  deploy:
    concurrency: deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Git Version
        id: version
        uses: codacy/git-version@2.7.1
        with:
          release-branch: main

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17

      - name: Setup and execute Gradle 'bootBuildImage' task
        uses: gradle/gradle-build-action@v2
        env:
          DOCKER_REGISTRY_PASSWORD: ${{ secrets.GHCR_SECRET }}
        with:
          arguments: |
            bootBuildImage 
            --imageName ghcr.io/moyaf/la-la-land-or-nicky-minaj:${{ steps.version.outputs.version }}
            --publishImage

      - name: Install flyctl
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl deploy --image ghcr.io/moyaf/blog-be:${{ steps.version.outputs.version }}
